kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nfs-mysql-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-mysql-provisioner
    spec:
      serviceAccount: mysql-nfs-provisioner
      containers:
        - name: nfs-mysql-provisioner
          image: registry.cn-hangzhou.aliyuncs.com/open-ali/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root-mysql
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: fuseim.pri/ifs
            - name: NFS_SERVER
              value: 192.168.1.11
            - name: NFS_PATH
              value: /usr/local/k8s/mysql
      volumes:
        - name: nfs-client-root-mysql
          nfs:
            server: 192.168.1.11
            path: /usr/local/k8s/mysql
